spring:
  application:
    name: movieflix-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/movieflix?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "carlogbossou.developpeur@gmail.com"
    password: "zrzavcigfkfrvhjq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


project:
  poster: posters/

security:
  jwt:
    access-token:
      expiration-minutes: 5
    refresh-token:
      expiration-days: 7
  secret-key: ChkdEVQYNkI1kAldPLKg9bHdvAo8BP+QZ38rRsaDF5c

  app:
    forgot-password:
      otp-expiration-seconds: 600

base:
  url: "http://localhost:8080"